/**
 * This proxy class is generated by `zx.io.remote.proxy.ClassWriter` and should not be edited manually
 * because it will be overwritten.
 *
 * To regenerate, use `zx create-proxies`, and the CMS server will automatically do the same during startup.
 *
 * Copyright and License - this file is copyright and licensed under the terms provided by the copyright owner, 
 * which presumably match the owner and license terms of the original source file.  It is your responsibility 
 * to determine ownership and terms.
 *

  
 * @use(zx.io.persistence.Object)
  
 * @use(qx.data.Array)
  


  
 * @require(zx.io.remote.anno.Property)
  

 */
qx.Class.define("zx.app.pages.UrlNode", {
  extend: zx.io.persistence.Object,
  
    include: [ zx.app.pages.MUrlNode ],
  

  construct(...vargs) {
    this.base(arguments, ...vargs);
    zx.io.remote.NetworkEndpoint.initialiseRemoteClass(zx.app.pages.UrlNode);
  },

  properties: {
    
      name: {
        
        
           check: "String", 
          nullable: false,
           event: "changeName", 
           apply: "_applyName", 
          
        
        "@": [new zx.io.remote.anno.Property()]
      },
    
      uuid: {
        
        
           check: "String", 
          nullable: false,
           event: "changeUuid", 
           apply: "_applyUuid", 
          
        
        "@": [new zx.io.remote.anno.Property()]
      },
    
      parent: {
         init: null, 
        
           check: "zx.io.persistence.Object", 
          nullable: true,
           event: "changeParent", 
           apply: "_applyParent", 
          
        
        "@": [new zx.io.remote.anno.Property()]
      },
    
      children: {
        
        
           check: "qx.data.Array", 
          nullable: false,
           event: "changeChildren", 
           apply: "_applyChildren", 
           transform: "_transformChildren", 
        
        "@": [new zx.io.remote.anno.Property()]
      },
    
  },

  members: {
    
      _applyName(value, oldValue) {
        // Nothing - to be overridden
      },
    
      _applyUuid(value, oldValue) {
        // Nothing - to be overridden
      },
    
      _applyParent(value, oldValue) {
        // Nothing - to be overridden
      },
    
      _applyChildren(value, oldValue) {
        // Nothing - to be overridden
      },
    

    
      

      
        _transformChildren(value, oldValue) {
        if (oldValue) {
          oldValue.replace(value);
          return oldValue;
        }

        return value;
      },
      
    
  }
});
