/**
 * This proxy class is generated by `zx.io.remote.proxy.ClassWriter` and should not be edited manually
 * because it will be overwritten.
 *
 * To regenerate, use `zx create-proxies`, and the CMS server will automatically do the same during startup.
 *
 * Copyright and License - this file is copyright and licensed under the terms provided by the copyright owner, 
 * which presumably match the owner and license terms of the original source file.  It is your responsibility 
 * to determine ownership and terms.
 *

  
 * @use(zx.app.pages.UrlNode)
  


  
 * @require(zx.io.remote.anno.Property)
  

 */
qx.Class.define("zx.app.pages.UrlTreeNavigator", {
  extend: zx.io.persistence.Object,
  

  construct(...vargs) {
    this.base(arguments, ...vargs);
    zx.io.remote.NetworkEndpoint.initialiseRemoteClass(zx.app.pages.UrlTreeNavigator);
  },

  properties: {
    
      rootNode: {
         init: null, 
        
           check: "zx.app.pages.UrlNode", 
          nullable: true,
           event: "changeRootNode", 
           apply: "_applyRootNode", 
          
        
        "@": [new zx.io.remote.anno.Property()]
      },
    
      prefix: {
         init: "pages", 
        
           check: "String", 
          nullable: true,
           event: "changePrefix", 
           apply: "_applyPrefix", 
          
        
        "@": [new zx.io.remote.anno.Property()]
      },
    
  },

  members: {
    
      _applyRootNode(value, oldValue) {
        // Nothing - to be overridden
      },
    
      _applyPrefix(value, oldValue) {
        // Nothing - to be overridden
      },
    

    
  }
});
