/**
 * This proxy class is generated by `zx.io.remote.proxy.ClassWriter` and should not be edited manually
 * because it will be overwritten.
 *
 * To regenerate, use `zx create-proxies`, and the CMS server will automatically do the same during startup.
 *
 * Copyright and License - this file is copyright and licensed under the terms provided by the copyright owner, 
 * which presumably match the owner and license terms of the original source file.  It is your responsibility 
 * to determine ownership and terms.
 *

  


  
 * @require(zx.io.remote.anno.Method)
  

 */
qx.Class.define("zx.server.Object", {
  extend: zx.io.persistence.Object,
  

  construct(...vargs) {
    this.base(arguments, ...vargs);
    zx.io.remote.NetworkEndpoint.initialiseRemoteClass(zx.server.Object);
  },

  properties: {
    
  },

  members: {
    

    
      
      "@save": [new zx.io.remote.anno.Method()],
      

      
        save() { 
          throw new Error("This object does not exist on the server yet, so remote method invocation is not possible");
        },
      
    
  }
});
