/**
 * This proxy class is generated by `zx.io.remote.proxy.ClassWriter` and should not be edited manually
 * because it will be overwritten.
 *
 * To regenerate, use `zx create-proxies`, and the CMS server will automatically do the same during startup.
 *
 * Copyright and License - this file is copyright and licensed under the terms provided by the copyright owner, 
 * which presumably match the owner and license terms of the original source file.  It is your responsibility 
 * to determine ownership and terms.
 *

  


  
 * @require(zx.io.persistence.anno.Property)
  
 * @require(zx.io.remote.anno.Property)
  

 */
qx.Class.define("zx.cms.content.ContentPiece", {
  extend: zx.cms.content.Piece,
  
    include: [ zx.cms.content.MContentPiece ],
  

  construct(...vargs) {
    this.base(arguments, ...vargs);
    zx.io.remote.NetworkEndpoint.initialiseRemoteClass(zx.cms.content.ContentPiece);
  },

  properties: {
    
      content: {
         init: "", 
        
           check: "String", 
          nullable: false,
           event: "changeContent", 
           apply: "_applyContent", 
          
        
        "@": [new zx.io.persistence.anno.Property(), new zx.io.remote.anno.Property()]
      },
    
      cssClass: {
         init: "", 
        
           check: "String", 
          nullable: false,
           event: "changeCssClass", 
           apply: "_applyCssClass", 
          
        
        "@": [new zx.io.persistence.anno.Property(), new zx.io.remote.anno.Property()]
      },
    
  },

  members: {
    
      _applyContent(value, oldValue) {
        // Nothing - to be overridden
      },
    
      _applyCssClass(value, oldValue) {
        // Nothing - to be overridden
      },
    

    
  }
});
