/**
 * This proxy class is generated by `zx.io.remote.proxy.ClassWriter` and should not be edited manually
 * because it will be overwritten.
 *
 * To regenerate, use `zx create-proxies`, and the CMS server will automatically do the same during startup.
 *
 * Copyright and License - this file is copyright and licensed under the terms provided by the copyright owner, 
 * which presumably match the owner and license terms of the original source file.  It is your responsibility 
 * to determine ownership and terms.
 *

  
 * @use(qx.data.Array)
  


  
 * @require(zx.io.persistence.anno.Property)
  
 * @require(zx.io.remote.anno.Property)
  

 */
qx.Class.define("zx.cms.website.NavItem", {
  extend: zx.io.persistence.Object,

  construct(...vargs) {
    this.base(arguments, ...vargs);
    zx.io.remote.NetworkEndpoint.initialiseRemoteClass(zx.cms.website.NavItem);
  },

  properties: {
    url: {
      check: "String",
      nullable: false,
      event: "changeUrl",
      apply: "_applyUrl",

      "@": [new zx.io.persistence.anno.Property(), new zx.io.remote.anno.Property()]
    },

    title: {
      check: "String",
      nullable: false,
      event: "changeTitle",
      apply: "_applyTitle",

      "@": [new zx.io.persistence.anno.Property(), new zx.io.remote.anno.Property()]
    },

    cssClass: {
      init: "",

      check: "String",
      nullable: false,
      event: "changeCssClass",
      apply: "_applyCssClass",

      "@": [new zx.io.persistence.anno.Property(), new zx.io.remote.anno.Property()]
    },

    children: {
      check: "qx.data.Array",
      nullable: false,
      event: "changeChildren",
      apply: "_applyChildren",
      transform: "_transformChildren",

      "@": [new zx.io.persistence.anno.Property().set({ embed: true }), new zx.io.remote.anno.Property()]
    }
  },

  members: {
    _applyUrl(value, oldValue) {
      // Nothing - to be overridden
    },

    _applyTitle(value, oldValue) {
      // Nothing - to be overridden
    },

    _applyCssClass(value, oldValue) {
      // Nothing - to be overridden
    },

    _applyChildren(value, oldValue) {
      // Nothing - to be overridden
    },

    _transformChildren(value, oldValue) {
      if (oldValue) {
        oldValue.replace(value);
        return oldValue;
      }

      return value;
    }
  }
});
