/**
 * This proxy class is generated by `zx.io.remote.proxy.ClassWriter` and should not be edited manually
 * because it will be overwritten.
 *
 * To regenerate, use `zx create-proxies`, and the CMS server will automatically do the same during startup.
 *
 * Copyright and License - this file is copyright and licensed under the terms provided by the copyright owner, 
 * which presumably match the owner and license terms of the original source file.  It is your responsibility 
 * to determine ownership and terms.
 *

  


  
 * @require(zx.io.persistence.anno.Property)
  
 * @require(zx.io.remote.anno.Property)
  

 */
qx.Class.define("zx.cms.system.ShortUrl", {
  extend: zx.server.Object,
  

  construct(...vargs) {
    this.base(arguments, ...vargs);
    zx.io.remote.NetworkEndpoint.initialiseRemoteClass(zx.cms.system.ShortUrl);
  },

  properties: {
    
      url: {
        
        
           check: "String", 
          nullable: false,
           event: "changeUrl", 
           apply: "_applyUrl", 
          
        
        "@": [new zx.io.persistence.anno.Property(), new zx.io.remote.anno.Property()]
      },
    
      shortCode: {
         init: null, 
        
           check: "String", 
          nullable: true,
           event: "changeShortCode", 
           apply: "_applyShortCode", 
          
        
        "@": [new zx.io.persistence.anno.Property(), new zx.io.remote.anno.Property()]
      },
    
      title: {
         init: null, 
        
           check: "String", 
          nullable: true,
           event: "changeTitle", 
           apply: "_applyTitle", 
          
        
        "@": [new zx.io.persistence.anno.Property(), new zx.io.remote.anno.Property()]
      },
    
      type: {
         init: "impersonate", 
        
           check: ["redirect","impersonate"], 
          nullable: false,
           event: "changeType", 
           apply: "_applyType", 
          
        
        "@": [new zx.io.persistence.anno.Property(), new zx.io.remote.anno.Property()]
      },
    
      value: {
         init: null, 
        
           check: "String", 
          nullable: true,
           event: "changeValue", 
           apply: "_applyValue", 
          
        
        "@": [new zx.io.persistence.anno.Property(), new zx.io.remote.anno.Property()]
      },
    
  },

  members: {
    
      _applyUrl(value, oldValue) {
        // Nothing - to be overridden
      },
    
      _applyShortCode(value, oldValue) {
        // Nothing - to be overridden
      },
    
      _applyTitle(value, oldValue) {
        // Nothing - to be overridden
      },
    
      _applyType(value, oldValue) {
        // Nothing - to be overridden
      },
    
      _applyValue(value, oldValue) {
        // Nothing - to be overridden
      },
    

    
  }
});
